/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.22
 * Generated at: 2020-01-15 08:24:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_00281_1_0029_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Float four columns side by side */\r\n");
      out.write(".column {\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 25%;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Remove extra left and right margins, due to padding */\r\n");
      out.write(".row {margin: 0 -5px;}\r\n");
      out.write("\r\n");
      out.write("/* Clear floats after the columns */\r\n");
      out.write(".row:after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  display: table;\r\n");
      out.write("  clear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive columns */\r\n");
      out.write("@media screen and (max-width: 600px) {\r\n");
      out.write("  .column {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the counter cards */\r\n");
      out.write(".card {\r\n");
      out.write("  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);\r\n");
      out.write("  padding: 16px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  background-color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write(".card {\r\n");
      out.write("  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);\r\n");
      out.write("  max-width: 300px;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-family: arial;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".price {\r\n");
      out.write("  color: red;\r\n");
      out.write("  font-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card button {\r\n");
      out.write("  border: none;\r\n");
      out.write("  outline: 0;\r\n");
      out.write("  padding: 12px;\r\n");
      out.write("  color: white;\r\n");
      out.write("  background-color: #000;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card button:hover {\r\n");
      out.write("  opacity: 0.7;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("  background-color: #4CAF50; /* Green */\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 15px 20px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".button1 {\r\n");
      out.write("  background-color: #4CAF50; /* Green */\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 15px 20px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"Pink\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"column\">\r\n");
      out.write("    <img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\1.jpg\" height=\"250px\" width=\"250px\">\r\n");
      out.write("    <h1>Formal White </h1>\r\n");
      out.write("  <p class=\"price\">Rs.1199</p>\r\n");
      out.write("  <p>Style-Formal wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  \r\n");
      out.write("  <a href=\"C:\\Users\\Lenovo\\eclipse-workspace\\PROJECT\\WebContent\\hindi_faculty.jsp\" class=\"button\">Add to Cart</a>\r\n");
      out.write("  \r\n");
      out.write("  <a href=\"C:\\Users\\Lenovo\\eclipse-workspace\\PROJECT\\WebContent\\hindi_lab.jsp\" class=\"button1\">Buy Now</a>\r\n");
      out.write("  \r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"column\">\r\n");
      out.write("    <img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\2.jpg\" height=\"250px\" width=\"250px\">\r\n");
      out.write("    <h1>Light Pink </h1>\r\n");
      out.write("  <p class=\"price\">Rs.999</p>\r\n");
      out.write("  <p>Style-Formal wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  <div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"column\">\r\n");
      out.write("    <img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\3.jpg\" height=\"250px\" width=\"250px\">\r\n");
      out.write("     <h1>Casual Shirt</h1>\r\n");
      out.write("  <p class=\"price\">Rs.999</p>\r\n");
      out.write("  <p>Style-Casual wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  <div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"column\">\r\n");
      out.write("    <img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\4.jpg\" height=\"250px\" width=\"250px\">\r\n");
      out.write("     <h1>Solid Cotton </h1>\r\n");
      out.write("  <p class=\"price\">Rs.1199</p>\r\n");
      out.write("  <p>Style-Casual wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("<div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"row\">\r\n");
      out.write("  <div class=\"column\">\r\n");
      out.write("    <img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\5.jpg\" height=\"250px\" width=\"250px\">\r\n");
      out.write("     <h1>Cotton Shirt</h1>\r\n");
      out.write("  <p class=\"price\">Rs.1199</p>\r\n");
      out.write("  <p>Style-Casual wear</p>\r\n");
      out.write(" <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  <div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"column\">\r\n");
      out.write("    <img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\6.jpg\" height=\"250px\" width=\"250px\">\r\n");
      out.write("     <h1>Grey Cotton </h1>\r\n");
      out.write("  <p class=\"price\">Rs.1299</p>\r\n");
      out.write("  <p>Style-Casual wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  <div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"column\">\r\n");
      out.write("    <img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\7.jpg\" height=\"250px\" width=\"250px\">\r\n");
      out.write("     <h1>Light Yellow </h1>\r\n");
      out.write("  <p class=\"price\">Rs.1499</p>\r\n");
      out.write("  <p>Style-Casual wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  <div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"column\">\r\n");
      out.write("    <img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\8.jpg\" height=\"250px\" width=\"250px\">\r\n");
      out.write("     <h1>Purple Solid </h1>\r\n");
      out.write("  <p class=\"price\">Rs.1099</p>\r\n");
      out.write("  <p>Style-Casual wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  <div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"column\">\r\n");
      out.write("    <img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\9.jpg\" height=\"250px\" width=\"250px\">\r\n");
      out.write("     <h1>Blue Solid </h1>\r\n");
      out.write("  <p class=\"price\">Rs.999</p>\r\n");
      out.write("  <p>Style-Casual wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  <div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"column\">\r\n");
      out.write("    <img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\10.jpg\"  height=\"250px\" width=\"250px\">\r\n");
      out.write("     <h1>Floral Casual</h1>\r\n");
      out.write("  <p class=\"price\">Rs.1999</p>\r\n");
      out.write("  <p>Style-Casual wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  <div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"column\">\r\n");
      out.write("   <img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\11.jpg\"  height=\"250px\" width=\"250px\">\r\n");
      out.write("   <h1>Solid Cotton </h1>\r\n");
      out.write("  <p class=\"price\">Rs.1199</p>\r\n");
      out.write("  <p>Style-Formal wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  <div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write(" </div>\r\n");
      out.write("   <div class=\"column\">\r\n");
      out.write("<img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\12.jpg\"  height=\"250px\" width=\"250px\">\r\n");
      out.write(" <h1>Solid Black </h1>\r\n");
      out.write("  <p class=\"price\">Rs.1099</p>\r\n");
      out.write("  <p>Style-Casual wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  <div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("   <div class=\"column\">\r\n");
      out.write("<img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\13.jpg\"  height=\"250px\" width=\"250px\">\r\n");
      out.write(" <h1>Solid Cotton </h1>\r\n");
      out.write("  <p class=\"price\">Rs.1099</p>\r\n");
      out.write("  <p>Style-Casual wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  <div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write("</div>\r\n");
      out.write(" <div class=\"column\">\r\n");
      out.write("<img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\14.jpg\"  height=\"250px\" width=\"250px\">\r\n");
      out.write(" <h1>Solid Cotton </h1>\r\n");
      out.write("  <p class=\"price\">Rs.1499</p>\r\n");
      out.write("  <p>Style-Formal wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  <div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"column\">\r\n");
      out.write("<img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\15.jpg\"  height=\"250px\" width=\"250px\">\r\n");
      out.write(" <h1>Royal Blue </h1>\r\n");
      out.write("  <p class=\"price\">Rs.1399</p>\r\n");
      out.write("  <p>Style-Party wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  <div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write("</div>\r\n");
      out.write(" <div class=\"column\">\r\n");
      out.write("<img src=\"C:\\Users\\user\\eclipse-workspace\\project 1\\WebContent\\men\\shirts\\16.jpg\"  height=\"250px\" width=\"250px\">\r\n");
      out.write(" <h1>Solid Shirt</h1>\r\n");
      out.write("  <p class=\"price\">Rs.1199</p>\r\n");
      out.write("  <p>Style-Formal wear</p>\r\n");
      out.write("  <p>Fabric-Cotton</p>\r\n");
      out.write("  <p>Sleeve-Full Sleeve</p>\r\n");
      out.write("  <p>Instruction-Do not bleach, dry in shade.</p>\r\n");
      out.write("  <div class=\"button\">Add to Cart</div>\r\n");
      out.write("  <div class=\"button1\">Buy Now</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
